# Generated by Django 4.0.4 on 2023-09-11 22:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplinaID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(max_length=50)),
                ('ano', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='deve introduzin um valor maior do que 0')])),
                ('semestre', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='deve introduzin um valor maior do que 0')])),
                ('ects', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='deve introduzin um valor maior do que 0')])),
                ('topicos', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagemID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(max_length=50)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='myPortfolio/')),
            ],
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituicaoID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Interesse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interesseID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoaID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(max_length=50)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecnologiaID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(max_length=50)),
                ('ano', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='deve introduzin um valor maior do que 0')])),
                ('cadeira', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myPortfolio.disciplina')),
                ('imagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myPortfolio.imagem')),
            ],
        ),
        migrations.CreateModel(
            name='Educacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educacaoID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('curso', models.CharField(max_length=50)),
                ('inicio', models.IntegerField(validators=[django.core.validators.MinValueValidator(1980, message='Value must be 1980 or grater'), django.core.validators.MaxValueValidator(2023, message='Value cannot be greater than current year')])),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='myPortfolio.instituicao')),
            ],
        ),
        migrations.AddField(
            model_name='disciplina',
            name='professor',
            field=models.ManyToManyField(related_name='disciplinas', to='myPortfolio.pessoa'),
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competenciaID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=200)),
                ('tipocompetencia', models.IntegerField(choices=[(1, 'Técnica'), (2, 'Organizativa)'), (3, 'Social'), (4, 'Linguística')], default=1)),
                ('projectos', models.ManyToManyField(related_name='competencias', to='myPortfolio.projeto')),
            ],
        ),
    ]
