# Generated by Django 4.0.4 on 2023-09-11 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myPortfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Educacao',
            new_name='Curso',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='educacaoID',
            new_name='cursoID',
        ),
    ]
