# Generated by Django 4.0.4 on 2023-09-11 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myPortfolio', '0002_rename_educacao_curso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='curso',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myPortfolio.curso'),
        ),
    ]
