# Generated by Django 4.0.4 on 2023-09-11 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myPortfolio', '0003_disciplina_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='myPortfolio.curso'),
        ),
    ]
