# Generated by Django 4.0.4 on 2023-09-11 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myPortfolio', '0004_alter_disciplina_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='curso',
        ),
    ]
