# Generated by Django 4.0.4 on 2023-09-11 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPortfolio', '0005_remove_disciplina_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='professor',
            field=models.ManyToManyField(related_name='leciona', to='myPortfolio.pessoa'),
        ),
    ]
