# Generated by Django 4.0.4 on 2023-09-11 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myPortfolio', '0006_alter_disciplina_professor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='cadeira',
        ),
        migrations.DeleteModel(
            name='Disciplina',
        ),
    ]
