# Generated by Django 4.0.4 on 2023-09-11 23:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myPortfolio', '0007_remove_projeto_cadeira_delete_disciplina'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplinaID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(max_length=50)),
                ('ano', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='deve introduzin um valor maior do que 0')])),
                ('semestre', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='deve introduzin um valor maior do que 0')])),
                ('ects', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='deve introduzin um valor maior do que 0')])),
                ('topicos', models.CharField(max_length=50)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='myPortfolio.curso')),
                ('professor', models.ManyToManyField(related_name='disciplinas', to='myPortfolio.pessoa')),
            ],
        ),
        migrations.AddField(
            model_name='projeto',
            name='cadeira',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myPortfolio.disciplina'),
            preserve_default=False,
        ),
    ]
