# Generated by Django 4.0.4 on 2023-09-11 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myPortfolio', '0008_disciplina_projeto_cadeira'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cadeiras', to='myPortfolio.curso'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='professor',
            field=models.ManyToManyField(related_name='leciona', to='myPortfolio.pessoa'),
        ),
    ]
