# Generated by Django 4.0.4 on 2023-09-12 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPortfolio', '0009_alter_disciplina_curso_alter_disciplina_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competencia',
            name='tipocompetencia',
            field=models.IntegerField(choices=[(1, 'Técnica'), (2, 'Organizativa'), (3, 'Social'), (4, 'Linguística')], default=1),
        ),
    ]
